local H = {}

H[0] = ' "NOT found" \n\n Most of this information is from the book: \n SETHURAMAN, GURUSWAMY. MY FORTUNE: THE MYSTIC KEY TO YOUR SUCCESS THROUGH NUMEROLOGY'

H[1] = 'I am yet to come across someone with a name like \'A\'! Anyways (we\'ve got to begin somewhere!), a person with a 1 name would do fairly well initially, but middle age crises would bog him down. Early on there is individuality and inventiveness. Later, inflexible and intractable. Heaps of confusion, with ego issues not letting any solutions through. So, it\'s inadvisable, even for people who number 1 would usually be lucky. The end is lonely.'

H[2] = 'This again, would be a really rare name! Still not helpful, though. A fluid mind, some choppy waters (Two is associated with the moon and water). Let\'s just say they would be emotional, to the point where logic would be overpowered quite often. All leading to a wasted life, and missed opportunities. A markedly timid persona, the challenge is to be resolute, to find balance.' 

H[3] = 'This name number denotes hard work, intelligence, success and a comfortable life. They will be highly educated and will gradually progress in life.'

H[4] = 'As this name number will be only for very short names, it signifies a person or a thing that is popular. It does not bring luck as one might deserve. They will have needless fears, sickness and opposition. They can be well informed and worldly-wise, but still they would work only as subordinates to others.'

H[5] = 'This number gives the power to charm people, exude dynamism and to lead a luxurious life enjoying fame and prominence. They spend money lavishly. These people should cultivate perseverance and concentration of mind.'

H[6] = 'This number signifies a peaceful life, a satisfied and contented mind and a good standard of living. A perfect number along with number 28. But this number has little power compared to #28. Although, as this number forms the basis of numbers : 15, 24, 33, 42, 51, 60, 69, 78, 87, 96, 105 it\'s lucky and auspicious qualities are given to all its double digit numbers. Symbolized by the thunderbolt.'

H[7] = 'This name number represents high principles and virtuous qualities, which may flourish with divine grace. Unexpected changes will take place. Efforts will not produce the desired results.'

H[8] = 'This Name number gives you great success in spiritual life. If they have no control over pleasures, success will be delayed. After a big struggle they may succeed. They will have to face unexpected dangers and difficult circumstances in life.'

H[9] = 'If the name comes under this number, it signifies wisdom and capability. It also denotes travel, struggles against odd situations and victory in the end. When they finally succeed, they will have a long life of luxury.'

H[10] = 'This number when comes as a name indicates the sound or resonance of the primal force. This is depicted in the ancient texts as a snake enmeshed within a wheel. Those named under this number will be dignified and popular. Confidence and patience co-exist in their lives but their fortunes will change frequently. It is like a revolving wheel, with frequent ups and downs. They must be honest in all their activities and they are bound to gain popularity. They will lead happy lives since there will be no paucity of funds. This is named \"The King\" by the Babylonians.'

H[11] = 'Those having 11 as their name number will come up in life by their sheer faith in God. They will profit by various means very easily. They may be riddled with unforeseen problems and dangers, as if their faith is being tested. Sometimes, they tend to meddle with matters that do not concern them. They are likely to be let down by their family and friends. If they have faith in God, they will definitely attain great heights in life. If they lack faith, they are bound to face a lot of setbacks.'

H[12] = 'These people naturally possess the ability to attract people by their power of speech. They sacrifice their lives for the welfare and happiness of others by shouldering their burdens too. Named \"The Call to Wisdom and Writing\". '

H[13] = 'People in the western countries regard this number as unlucky and ominous. They do not stay in rooms or houses having this number and some hotels even do not have rooms with this number. Unexpected events of sorrowful nature occur frequently. Men of this number have bitter experiences and face a lot of difficulties because of women. Though these people do manage to come up in life materially, they would still lead lives full of struggles. This is not a desirable name number. This number gives only severe grief, if birth and destiny numbers are also unlucky.'

H[14] = 'This number is suitable for trade. Those having this Name number are always surrounded by a lot of people and things. They are successful in various trades and will meet a lot of friends. They may have strange problems and may face disappointments by trusting others. They may also face risk from thunder, lightning, water and fire. They undertake frequent travels. These people are advised to be careful while travelling in fast-moving vehicles. If the product in which they trade also comes under number 14, it will have excellent public patronage. The matters concerning love and marriage must be considered and reconsidered many times before a decision is taken. If not, these people may marry in haste and repent at leisure. This number can be called a very lucky number.'

H[15] = '\"Venus The Queen of Heaven\" \n This is number is the planet Venus in its purest form and is one of the most powerful numbers in its own unique way. Named \"The Queen of Heaven\". This brings the determination to succeed in all the plans and earn money and the quest for achieving one’s ends are signified by this number. Lust, revenge and malice may push the people of this Name number to a vile state of mind. They may become selfish gradually. A charming appearance and forceful speech will help them in achieving their interests. Though this name number is not one conducive to leading a virtuous life, it is one that is ideally suited for purely material success. An alluring personality, excellence in fine arts and a witty nature yield positive results in any activity that can generate huge profits. Many people come forward to help them in need. Life will be luxurious. If their birth number is also favorable, these people will attain fame, wealth and distinction in all aspects of life.'

H[16] = 'This number signifies speedy progress and a sudden downfall. Ancient texts depict this number by a picture showing the shattering of a tall tower and a king’s head with his crown falling from its top. This truth was proved when Japan (16) fell prey to the nuclear bombs. The Japanese Emperor was considered to be God-incarnate and his people would not even look at him from an elevated place. Unfortunately, the Americans bombed Japan stripping the Emperor of his status and the consequences are well known even today. If your name number is 16, it is better to change it to some other lucky number. This number induces new imaginative thoughts which will be reflected in the writings of the person.'

H[17] = ' \"The Star of Algorab\" \n This name number gives demonic qualities while pursuing the goals. It brings many problems and trials. However, they will persistently struggle without giving up. Failures will prompt them to struggle more actively. In the end they will be successful, and they get permanent prosperity and great fame. Some of them risk their lives to attain their goals and so achieve progress. The world can never forget them. This number can give mystic powers also.'

H[18] = '\"The Star of Algol\" \n This name number, which signifies the decline of divinity, will bring in problems, procrastination in all matters, deviousness, and dangerous enemies. Their selfishness may include them to indulge in antisocial activities. They follow evil ways consciously and become highly selfish. Life devoid of peace and rest will be the order of the day. This number signifies growth of personal desires at the cost of virtue. Desires will come to an end. Divine grace will get destroyed. This number, which denotes jealousy, malice and dangers due to fire and weapons, is not considered desirable.'

H[19] = ' \" The Star of Sirius\" \n Ancient books on this subject attribute mastery over the Three Worlds to this Number and as such, these people will be the focus of attention wherever they are. This number indicates the Rising Sun. This also has been described as the “Prince of the Celestial World” in ancient Indian texts and as an “Ideal Lover” in Egyptian scriptures. The sun becomes brighter as the day lengthens and so also these people progress as their age advances. Position, status, happiness, success and wealth will be gradually on the rise. Being well-disciplined, they will look young and will be very active even in their advanced age. They must be honest even in matters related to sensual pleasures.'

H[20] = 'This spiritual number represents a drumbeat heralding triumph or victory. People having this Name number work for liberation and social reforms. They are capable of providing relief to the masses from grief and struggles. The world will admire them. When they work with selfish motives, they are extremely dangerous and highly destructive. Those with name number 20 may excel in medical practice using toxic medicines and dealing with poisonous drugs. They possess the ability to awaken the sleeping masses and lead them to very great achievements. When they go out of their way to satisfy their selfish needs, they are bound to meet with failure or disaster. (Hitler, born on the 20th, spurred Germany into war and faced a humiliating defeat. He is a very good example of this Name number. He was represented by the battle drum that goaded the people to pursue a selfish goal which led to destruction). Symbolized by the \"The God of Justice\" of the Babylonians.'

H[21] = 'These people are self-centered and concerned about their own happiness and matters profitable to them. With great determination, they rise steadily in life and reach the pinnacle of success. Their tactful behavior helps them to solve all their problems. They struggle hard in their early days but achieve success and happiness as they grow up. They will attain and retain good positions permanently in their lives.'

H[22] = 'The characteristics of those born on the 22nd hold equally good for this Name number also. This number instigates base feelings and emotions. They are drawn towards gambling, drinking, speculation and other vices and will readily indulge in them. They may move towards self-destruction at a great speed and are generally surrounded by wicked and fraudulent people. They invariably earn a bad reputation. They dislike the counsel of others. If the influence of their date of birth is favorable, they can be successful. Otherwise, they have to struggle to prevent total failure. Those with selfish motives invariably urge these people to devious ways in order to further their own interests. They are good administrators and can meet any problem or difficulty with courage. Dangerous circumstances are foreseen. They often face humiliations.'

H[23] = '\"The Royal Star of Regulus\" \n This number is the luckiest of all Mercury (5) numbers. These people find success in all their endeavors. All their plans will succeed. They can achieve things which others won’t even imagine. Their accomplishments will astonish those around them. In spite of being such lucky people, if they do not strive hard, they would be enjoying luxuries that they are not worthy of. Since they succeed in all their efforts, they will earn the patronage, respect, honor and favor of people in very high positions. Hence, these people are advised to keep up high standards and work out plans to achieve their goals. If not, they might end up leading lives of luxury and pomp devoid of any personal accomplishment. The positive types among them are the most-sought-after type executives in governments or in private enterprises. The negative types devote time to sleep and day-dreaming.'

H[24] = 'Those named under this number 24 will receive many favors from the government. This number helps. them to reach very high positions in their careers easily. They will marry those who are much higher in status and wealth. If the name number comes under 24, these people can be found progressing very fast in uniformed service like the Defense, Paramilitary forces and the Police. Even if they join as the lowest rank in any field, this number will help them to rise to very high position by its powerful vibrations.'

H[25] = 'As this number gives good results in the end, it can be considered a good number. These people will undergo many trials in life. Every step in life will present problems and difficulties. The victory gained over such problems will give them self-confidence, spiritual growth and the support of those around them. They are worldly-wise, known for clarity of thought and hence their actions will be well-planned. These people will establish ideals and standards for themselves and will adhere to them at all costs. Just as gold when cleansed of all impurities becomes shiny and precious, the lives of these people will end with respect and honor after many trials. (Note the life of Mahatma Gandhi who used to sign as M.K.Gandhi).'

H[26] = 'This number denotes poverty in old age and fruitless efforts. Those who have this name number undergo great losses due to friends and partners. Circumstances lead them to failure and confusion. This number reduces one’s span of life and earns enemies who may even go to the extent of murdering them. Those with Name numbers 26 at first begin their life with great principles and later change their minds and end up only in pursuit of money and status. (Based on their general qualities of number 8, they will be a little more fortunate in their later years).'

H[27] = 'This number signifies a clear mind and intelligence, unceasing hard work, accumulation of wealth, all round influence and positions of prominence and high rank. Especially in uniformed services like police, army, etc., they will rise very high in their ranks. This is as fortunate as number 24, which has been explained earlier in this book. They will be respected and treated as the best in their profession or service. They like to do social service and will be involved also in matters that would benefit them. This is a very fortunate number that brings spirituality and magical powers.'

H[28] = 'Technically this is the most powerful number one can have. This number is a perfect number (along with 6) But this number symbolizes pure raw power with no constructive outlet. The word \"POWER\" holds the value of 28 in Chaldean numerology. Those with this name number do progress and get all the comforts during the early part of life but they frequently face struggles or difficulties in all their endeavors in life. They may have to start their lives again and again always afresh, many times over. Although they progress very fast in their lives, they finally lose everything due to the cruel stroke of fate. One of the examples of such people born under this number is General MacArthur, a fine soldier who deserved more of honor and recognition, but was deprived of his position and career by President Truman of USA! Those coming under this number may incur unexpected losses due to their friends and relatives. Money lent by them rarely comes back. As such, this number can only be regarded as an unlucky one, since all the hard-earned money may be lost unexpectedly.'

H[29] = 'Those under this Name number often find it necessary to go to court to settle disputes. They will experience all sorts of problems in their families and will generally be let down by family and friends. Those who praised them yesterday may curse them today. These people live a life of mental agony and sorrow with their life partner. They get into deep troubles with the opposite sex. Any remedial measures taken to come out of such troubles may result in delayed solutions and huge loss of money and this aggravates the existing problem too. The personal life will be full of ups and downs. Family life consists of events similar to the feats in a circus! Unless the name number is corrected properly, these people will encounter problems forever.'

H[30] = 'These people tend to live in a world of fantasy. They are wise thinkers. They like to do what they feel is right. At times, just for their own satisfaction they get involved in certain difficult tasks, without expecting any returns. They have less interest in making money. They know their minds and conquer the same easily. They gain mystic powers through mind control and related mental exercises. Named the \"Lord of Wisdom\".'

H[31] = 'These people do not care for profit or loss but want only the freedom to do what they desire. Whatever may be the gain involved, they would not like to indulge in anything against their wish. They evince interest in astrology, philosophy and related sciences. These people do not care about what others do or say about them. They only wish to succeed and are never keen on the monetary benefits they gain from such successes. Having succeeded, they sometimes even forgo their due profits. By the 31st year they lose all their material possession and savings. They regain them only by the age of 37. Unexpected happenings will bring about major changes in life. Even their death will be sudden and abrupt. However, when death draws nearer, they somehow become intuitive and sense it well in advance. If their birth number is 1 of any month, this number helps them to achieve great positions in their official career'

H[32] = 'This number can attract a variety of people. They have a mass appeal and they come out with unique ideas and techniques even without prior experience. This potent and forceful number can make anyone a prominent person. If they lead their life exploiting their intuition, life will be wonderful. If they listen to the advice of others, failures may recur one after another. This number is said to be the epitome of wisdom and intuition. They have above-average intelligence and a witty manner of speaking. They will become geniuses. Ups and downs will be common in their lives. They will attain high positions in life and will be youthful in appearance even in old age.'

H[33] = 'This number signifies simultaneous growth in divine grace and prosperity. Those with this name number with or without their knowledge attain spiritual enlightenment surprisingly. Along with divine grace, they are blessed with abundant wealth and properties like granaries, mills etc. They will have many luxurious things at their disposal. They may have everlasting wealth.'

H[34] = ' "The Star of Capella" \n In a way, this number can also be called lucky. This number will openly display the best qualities and capabilities of these persons in an attractive manner. It improves their stature but cannot be considered as fortunate. If the birth number is also a favorable one, they can earn enormous wealth quite easily. If not, earning money itself will become a problem. There will be some problem in their family life. Most of the men will either be addicted to women or wine. Their minds easily succumb to sensuous pleasures. This is the most fearful aspect of this number. (Be cautious about it)! Hence, they are advised to change this Name number to a more fortunate one.'

H[35] = 'This number outwardly seems to be fortunate but the person will suffer losses because of friends and associates. These people will become very rich and popular but later lose all their money. Unexpected accidents may happen. This number helps in earning money through illegal means. Today’s friends will become tomorrow’s foes. They are very fickle - minded. Expenses will mount. This number would create severe incurable pain in the stomach. (For those with heart problems, this Name number will be a curative factor). Those with this name number must be very careful in their large business endeavors.'

H[36] = '"The Star of Vega" \n This number can raise even poor people to an enviable status and make them live in mansions. Only when these people go away from their place of birth to distant regions, do they attain success. They will travel extensively and occupy high positions. This number, though it appears very fortunate, will cause problems within the family. They may be surrounded by disloyal people.'

H[37] = '"The Royal Star of Aldebaran" \n This is a very lucky number. It will lift even an ordinary person to the most prominent positions in life. It brings success in love and the patronage of the elite. These people will have good friends from both sexes. They will be greatly favored by men if they are women and vice versa. As a result, their lives will improve greatly. People will come forward to invest their capital with such people. Accumulation of money and wealth will be easy through various means. They will have an active interest in the fine arts and in all probability, lead comfortable and luxurious lives. They will be renowned for their pleasing manners and countenance. Some of them will be philanderers because of their casual attitude towards opposite sex. This number, which gives unexpected success, is a desirable one. "\n(Note: If people who occupy very high positions have their names under this number, it may bring them unnecessary problems. This number will bring good fortune to ordinary people. These people should remain satisfied when they attain a certain position in life and should not be too ambitious. This number, will bring fortune automatically, but will lose its power when one becomes too greedy.)"'

H[38] = ' "The Star of Procyon\n" The people under this name number will be honest, peace loving and gentle. When it is a name number of a person or a business, it will earn the help of the influential. This Name number can bring great success. People under this number will make rapid development and earn fame and wealth even from very humble beginnings. At times, they will face a lot of dangers and get cheated by bad people, resulting in unforeseen difficulties. Even their death will be sudden, rather unexpected and unusual.'

H[39] = 'These people are very sincere and hardworking. Invariably, the name and fame that are rightfully due to them will be enjoyed by others. They work unceasingly for the welfare of others. They are not as healthy as the other Number 3 people at some stage of their life and are prone to some kind of skin diseases.'

H[40] = 'Those under this number earn good friends, who will be of immense help to them in gaining jobs and positions of distinction. It provides accumulation of fine jewelry and wealth. It also brings fame and prosperity. Yet it is their negative qualities that are noticed by others. They can perform any work without any fear. Eventually, their lives will turn out to be fruitless and in vain. They will lose all their money. They will blame the society for not recognizing their services or help. Lot of problems will come up in their lives and the end will be pathetic. This number is represented by the constellation "Square of Pegasus" and the God of Mischief; Therefore, this is a strong number.'

H[41] = ' "The Star of Deneb Algedi\n" This number denotes the qualities of charming and controlling. They are renowned achievers and they have high ideals. They are keen about their development and will be world-famous. When they become heady with success, they get into things or matters which are beyond their capability. The failures that could result from such situations will be cleverly hidden from the public scrutiny. They are found to lead successful lives.'

H[42] = 'Those named under this number, even if they are poor at the beginning of their lives, will attain a very prominent rank or position in their careers. They may be greedy at times. They will have thrifty bent of mind and are smart in saving money. They hesitate to part with money even for their own comforts in life. Strength of mind and grace will flourish.'

H[43] = 'This is a strange number. Their whole life will be revolutionary. Whatever profession in which they are involved, this number produces new enemies. They have the tendency to resign from their jobs often. They will be constantly bringing out extreme ideas. They have extraordinary powers of imagination, speaking and writing as in the case of the other name numbers under 7. Their desires will be fulfilled at the end. This number, which is regarded as somewhat unlucky, indicates trials, great obstacles and revolutionary changes. They are sure to succeed in their ideals. (It is unlucky in the sense that they do not enjoy the luxuries or comforts of a peaceful life. Even their success will not yield them any personal gains). Their shrewdness increases with age, but they will encounter more criticism than praise for their capabilities and intelligence.'

H[44] = 'This number helps in earning money easily. Industries involving many people, like cinema theaters, printing presses, coal and iron mining, painting, making of furniture and sports goods, and organizing contests will help them earn a good income. Hiring out vehicles like buses, trucks and cars will also be rewarding. They can also run banks. One day everything may come to a halt. Only the owner will enjoy the profits in a proprietary concern. There is danger from fire and collapse of building. This number indicates that they may have to spend some time in prison. Their minds will go astray towards bad ways. Their lives may be comfortable outside prison. Generally, either they suffer from some disease or spend some time in prison, especially when the birth and destiny numbers are also not harmonious.'

H[45] = 'This is a lucky Name number. Even those who struggle at lower levels will rise to a higher status and positions. They are good conversationalists and will be found in gatherings that involve entertaining people. These hard-working people will earn outstanding positions in their career. They will achieve their goals at any cost. People would wonder if their life was a big show. Even though they may have nagging problems, they will retain their smile and will never allow anyone to know their problems. This number, which assures a comfortable life, fame and wealth, is a desirable one. Diseases will also be cured.'

H[46] = 'This has been described as the “Crowned Head” in the ancient texts. It means that when prudence, intelligence and knowledge are used wisely, it will bring the crown of life. Whatever may be the business, this number will help one to reach the pinnacle of success and is capable of raising even the most ordinary person to the position of a ruler. Wealth and status will go up with the advancement of age. People belonging to this number should be honest in all walks of life.'

H[47] = 'Those who come up very fast in the life can be seen amongst the people having this name number. They will be very much concerned about their own progress and will work out plans to achieve the same and will not rest until they reach their goal. As for as money matters are concerned, they will be very lucky and can be considered as fortunate people. Many people of this number tend to lose their eyesight at one stage. Even the best available treatment maybe in vain and they suffer very much. It is better for those interested in the habit of hunting to abstain from it and also from flesh-eating.'

H[48] = 'They will be more interested in religious matters, but face opposition in matters that involve the society at large. They will do a lot of work for public welfare, and create problems for themselves while attempting to do things beyond their capacity. Fate is against them most of the time.'

H[49] = 'This name number brings abundant riches. Their fame will spread far and wide and their achievements will be the envy of others. They lead highly eventful lives and travel a lot. Wonderful experiences, permanent prosperity, excellent properties and sudden fortunes will come to them. Accidents can also happen suddenly. If the birth number is a fortunate one, they lead happy lives. If not, they can end up being hated by others in the society and life will end in a tragic manner. This number kindles the power of imagination.'

H[50] = '"The Bull of Heaven". These people are very intelligent and analyze everything thoroughly. They excel in education. Some people will shine as good teachers. Some others use their intelligence to make money. They are lucky after the age of 50. Their life span will improve and they live longer.'

H[51] = '"The Royal Star of Fomalhaut\n"This is the most powerful of all numbers under six. It signifies sudden progress. Those who were just commoners yesterday will become popular and prominent to-day. Unusual circumstances will bring about an unexpected ascent in rank and status. Their body and mind will be bubbling with energy and become uncontrollable. They will be frequently lost in thought, or will become emotionally active and put in untiring efforts in their work. These people who are active in body and mind cannot sleep peacefully. They become restless like a caged lion. To be precise, these people will be ruled by an extra-ordinary energy or power of both body and mind. As there is a possibility of these people making enemies who could threaten their lives, it is advisable for them not to hurt others’ sentiments or feelings. This number is considered to be fortunate, as it signifies the accumulation of abundant wealth.'

H[52] = 'This number also signifies some type of revolutionary qualities. If the birth number is favorable it could bring world renown. They readily offer a solution to any problem and can charm many. If they are on the spiritual path, they can attain great powers and immense popularity. All their desires will be fulfilled. They can bring about a new era in the lives of others. (This power can also be found in number 25 to a certain extent). Their end will come abruptly, leaving their work unaccomplished. Although their personal life will be fraught with problems, they are sure to be famous and favored by all.'

H[53] = 'They experience success and failure in the beginning of life itself. As they grow older, their lives will become steadier and they will become well-known. Though they are intelligent, they are bound to get into problems beyond their control. These people, who can convert failure into success, will perform good deeds and earn prestige and popularity. (This is an unstable number. Only if the birth number is favorable, will it bring desirable effects). They will be lucky in their old age.'

H[54] = 'This number will give success step by step. Failures may also happen. They may begin their lives with prestige, reputation and prosperity. Stubbornness and thoughtless decisions will make them lose their name and fame. Greed is their worst enemy that could make them lose all their wealth if they are not careful. In the fag end of their lives, they may achieve peace and success. Their life will be without freedom and they will be under the control of others.'

H[55] = 'This number predicts that both creation and destruction can be done by a single power. This will bring victory over enemies. Before entering the battlefield, Greek soldiers were ordered to wear a talisman marked with number 55 around their necks. This number is the epitome of will-power and intuition. People under this number will astonish others by their knowledge and win them over. They are acknowledged as scholars. Wisdom and intelligence will be as bright as lightning. If not used in a proper way, this may destroy them. Knowledge in various subjects could be acquired by those born under this number.'

H[56] = 'This number is full of wonders. Though this number tends to bring fortune and fame, it is used by those practicing various forms of occultism and divination. This number can free a person from all ties and can break shackles of any kind. Locks would open automatically by their supernatural powers. Even the animals inside the cage would find their way out. As too much of an explanation would not be conducive for a clear thinking, I do not wish to pursue this subject any further. (As explained earlier, the number 29 represents powers of the body and mind, whereas Number 56 gives magical powers). These people will lose their wealth and fame all of a sudden.'

H[57] = 'This number gives victory or success in the beginning, but brings about gradual downfall and loss of interest in the end. Life which progresses at a very swift pace will grind to a halt all of a sudden. People named under this number will achieve great heights from humble beginnings but will later revert to their original positions.'

H[58] = 'This number gives outstanding popularity and the power to captivate others. They are great achievers. Life’s progress will be swift. They are pious and orthodox and are great reformers, though attached to religion. If their birth number is 4 or 8 of any month, they will hold positions of great responsibility and fame. They may be sometimes forced to carry out certain things against their wish. Outwardly, these people appear to be very lucky but they also have a lot of unwanted fears within. If the names of those born under other birth numbers also come under this number, life will slowly take a turn for the worse and they will lose their reputation. They may become selfish and may have to undergo a lot of difficulties during their lifetime.'

H[59] = 'Similar to persons belonging to number 50, these people are also research-minded. Their writings are full of humor and they would shine as “Humor Kings” among writers. They would become rich by writing and get excellent public support. Their aim will be to earn money. They will enjoy permanent fortunes. They may suffer from nervous diseases including paralysis. Hence, it is necessary for them to have good habits and keep themselves healthy.'

H[60] = 'This number signifies peace, prosperity, appreciation of fine arts, a balanced state of mind and wisdom. They are skilled conversationalists who can put forth very logical arguments. Their family life will be happy and idealistic. This is quite a fortunate number and is symbolized by the "The Royal Tiara".'

H[61] = 'These people will quit a comfortable life and try new avenues according to their wishes. Successes and failures come in succession. If they can take care of their health, their later years will be quite fruitful helping them win prestigious posts. Though they may seem to be leading happy lives, in reality, they will be unhappy in their family lives. They spend much time in making new efforts and will achieve victory. They will earn great fame.'

H[62] = 'Generally, it will give great fame, victories and a comfortable life. At times, great dangers and failures alternatively affect them. It could bring about serious enmity. It also causes misunderstanding among relatives. Family life will not be pleasant. Intellectual faculties will improve. These people can charm everyone easily. This name number helps in charming enemies too!'

H[63] = 'This is also a lucky number. However, if this comes as a Name number, it might lead one to wrong path. The ancient texts describe this number as one related to devious means, so the less said, the better!'

H[64] = 'This number will create equal number of friends and foes. Opposition will be experienced in life. This gives extraordinary will power, intelligence and knowledge. This will bestow fame by enabling them to do things that are considered impossible. This ensures high position in the Government. At times, this will give such a high position that everyone will pay respect and hold these people in high esteem and awe. Their words would cast a powerful influence.'

H[65] = '"The Royal Star of Antares\n"This number denotes divine grace and progress in spiritual life. It will earn the support of wealthy and powerful patrons. Marital life will be blissful. Persons under this Name number may be sometimes injured in accidents and may have cuts or bruises on their bodies.'

H[66] = ' "The Star of Alphecca" \n This number denotes dynamism and oratorical skills, perfection in the fine arts, patronage from the government authorities and also a comfortable life.'

H[67] = 'These people are exemplary artists (they may be artistes who perform) and work with great determination and vigor. They are patronized by power barons and they reveal noble ideas. (Men should control passions and lust for women.) Love, affection and grace make these people endearing. They can never achieve anything if they are selfish. This number, which helps to attract and conquer others, does not help non-artists.'

H[68] = 'This number is lucky to a certain extent. However, life that starts quite pleasantly may suddenly grind to a halt. They will get involved in schemes that they cannot execute and will be badly hurt. Their greed will spoil their career and life. The fortunes that came through an unforeseen stroke of luck may soon disappear. Hence, this number is not quite fortunate.'

H[69] = 'The person named under this number will be like an uncrowned king in any business they are involved in. They overtake others and retain their position safely by their own efforts. They are majestic in appearance, very prosperous and will achieve awe-inspiring status. Spurred by emotions, they are known to spend money lavishly for their self-satisfaction. They possess majesty and will lead extremely comfortable and luxurious lives. They are incomparable when it comes to charming others with their tact and speech.'

H[70] = 'People represented by this number are of extreme nature. Their comfortable life gets disturbed by circumstances. There are frequent disappointments, failures and problems. But the later years will be fruitful, successful and filled with blessings. This number does not possess much power. If their destiny number is favorable, these people will be happy during their final years. If not, their problems may drown them in misery.'

H[71] = 'This number which brings about obstacles initially will later shower prosperity. They will be good counselors to others because of their intelligence. This number may be considered fortunate.'

H[72] = ' "The Star of Spica\n" This is the best of all numbers under 9. Although these people struggle in their early years, they later enjoy life with all comforts. A mind devoid of doubt will be filled with joy. The wealth acquired by these people will remain intact in their family for many future generations. Money keeps oncoming continuously, without fail. (Businessmen should take note of this advantageous number). It will also bring repute. This number signifies permanent wealth.'

H[73] = 'This name number strengthens mental faculties and bestows fame, wealth and power. People having this number will aspire to lead comfortable lives and will accomplish their desires. Support from the people of authority will be available and material possessions will be in plenty. If they are not honest, they will lose their fame. If they are the spiritual types, they will lead a peaceful and comfortable life with pure hearts and noble thoughts.'

H[74] = 'These people have great affinity towards their religion. They run short of money often. They will introduce social and religious reforms and spread their principles. However, this is not a desirable name number, as it is best suited only for hermits and priests and is not favorable to others. Those who have this name number always remain worried about something or the other.'

H[75] = 'All of a sudden they attain great fame. They will make good friends very soon. Unexpectedly, they become very popular. Fame and comforts will come in search of them. They become good poets and writers.'

H[76] = 'Those having this name number lose all their worldly possessions at some point of time. They are very popular. They will be successful in philanthropic deeds. Surprisingly, they make money in new ways. Income or material gains come through unexpected means. Their last years are generally spent in solitude, doing nothing but eating and sleeping.'

H[77] = 'This number denotes sincere effort, self-confidence and hard work. Support from others brings in profits, fame and honor. Life will be very enchanting. They reap full benefits of this number only if they repose faith in god. They get chances to travel aboard.'

H[78] = 'They are the most righteous type among all the Number 6 people. They have a great leaning towards their religion and sometimes follow orthodox beliefs. They can become good poets and can bring the listeners under their spell. They are very generous and are fond of social service. They earn or inherit large sums of money very easily. But, if they are not careful, they could lose all their possessions except the Divine grace. Some of them attain success in occult practice and will be respected by one and all in society.'

H[79] = '"The Star of Polaris"\nPeople of this number tend to suffer very badly in the beginning of their lives due to many difficulties. Later, these people will rise quickly by their cleverness and sheer will power. They will settle down very comfortably and will succeed in their endeavors. They will have popular support, a comfortable life and will achieve enduring success. They become very fortunate with the passage of time and also become great personalities.'

H[80] = 'This number has strange mystic powers, but may lead to grave dangers if the date of birth is not favorable. Research in theology will be successful. Nature will change its course and help them. Though their lives are full of dangers and anxieties, they will be comfortable. Miracles will happen. It is a fortunate number.'

H[81] = 'This number signifies a fortunate life. This will give development, good position and wealth. If these people are not careful, their luck could change for the worse. They will have opportunities to become teachers.'

H[82] = '"The Star of Arcturus\n"This is one of the most powerful numbers and it can elevate even an ordinary person to the status of a ruler. Those having this number in their names are duty-conscious. With unceasing efforts, they will dominate the scene in any field they are placed in. They would own lands, gold mines and precious gems. They are lovers of high-bred horses and will attain the pinnacle of fame by making a fortune either in horse races, car races or in similar sports or business. They create unnecessary problems in their love matters and will be over-adamant in nature. Their eyes have magnetic powers. If the power of this number is properly understood and practiced, no physical or mental feat is impossible to perform.'

H[83] = 'This Name Number bestows prestigious posts which will earn the respect and adoration of many. They will achieve a life of splendor and authority. These people may be considered successful. This name number is seen in politics often.'

H[84] = 'Early days will be full of struggles and worries. They earn enemies unnecessarily. Travelling benefits, them. They do not get rewards commensurate to their efforts. They improve themselves to some extent spiritually. Though generally lacking in enthusiasm at first, they can go to extremes, if need be! If the influence of their birth date is favorable, they can be great achievers.'

H[85] = 'This name number signifies those who come up the hard way. They not only overcome all afflictions, but help in solving others’ problems too. They reveal new ideas about religion and nature. They shine well in the field of medicine. They generally attain a position of distinction and honor.'

H[86] = 'This number denotes those who come up in a gradual manner and the hard way. They get what they deserve. They earn the favor and help of rich people. With the help so received, they will lead comfortable and happy lives. They will have good savings and lead happy lives.'

H[87] = 'This number can give mystic powers. Money will be earned by devious and illegal means. In case of a “negative swing”, this number makes people steal at midnight and helps them to charm snakes and tame animals. If birth and destiny numbers are not positive, this number could be related to criminals and bad people. So, the less we discuss, the better.'

H[88] = 'This number gives spiritual progress. They are generous and compassionate. They are affectionate to all creatures and will become popular.'

H[89] = 'This number, which also signifies benefits, brings problems initially. They have a helping tendency and they will acquire great riches like land, houses and jewelry. Women are attracted to them easily. Society will respect the women of this Name number. They have a combination of beauty and wealth. They lead fearless lives with the help of their great power of speech and action. Initially, fire accidents may occur in their lives.'

H[90] = 'As this number derives its full power from number 9, its people will go to any extent to get their desires fulfilled. Victory will be certain. They will become very wealthy and famous. For those who are interested in spiritual pursuits this number is not desirable.'

H[91] = 'This indicates strong determination and profitable journeys. They also undertake many journeys for trade or otherwise and will do all things with great vigor. Maritime trade using boats and ships will bring them plenty of wealth. They can attain success in yogic exercises like meditation or concentration. Comfortable living awaits them.'

H[92] = 'This number signifies gold, silver, land, wealth and possession of yogic power. If people having this Name number can carefully practice the art of yogic breathing, they may even acquire the power of Astral projection.'

H[93] = 'These people are capable of doing marvelous things. They improve their worldly knowledge and are lucky to have their desires fulfilled. They excel in the field of histrionics through which they attain more fame. They earn through many business pursuits and lead very dignified lives.'

H[94] = 'These people execute lots of good services for the sake of mankind in general. They bring reforms in society. Comfort and fame will come and go in their lives. Their fame and good work will generally be remembered even after their demise. This is a fortunate name number.'

H[95] = 'This number signifies a disciplined life combined with daring events and honor. They are successful in trade and achieve distinction. By trading in a variety of new things, they amass wealth. They are excellent orators and will become popular in their line of business.'

H[96] = 'This can give a combination of prosperity and higher education. All desires will be fulfilled. They can excel in the fine arts easily. Women will be charmed easily by these people. This is a fortunate number.'

H[97] = 'This number gives proficiency in the scriptures and fine arts. It also gives eminence in spiritual career. They will be successful in all their efforts and will be prosperous due to their astounding achievements in chosen fields.'

H[98] = 'Like the people under Number 71, these people are also intelligent. But their lives are filled with worries and desires. Though they are intelligent, they may not benefit from that quality. Difficulties and chronic diseases may affect them.'

H[99] = 'This Name number will lure its native to devious ways. Success will come along with enmity. This number signifies being attacked by enemies, and hence it is not a good number. (However they will be blessed with education, wealth and prosperity).'

H[100] = 'Even though this number is capable of giving success in all efforts, it will not offer many opportunities. There will be plenty of money. This number implies a long and comfortable life, without any major achievements.'

H[101] = 'Those under this name number will be helped by governments or by the people of authority rather than by their own efforts. There will be lots of obstacles in their business. Slump in business will be common. This cannot be considered a lucky number.'

H[102] = 'This number signifies success at first, followed by struggles and confusion. These people cannot be called lucky.'

H[103] = 'This name number is also favorable. There will be improvement in material success initially, followed by a change in business. They will face a lot of competition. Later years will be pleasant and comfortable.'

H[104] = 'This number will bring success in life followed by unexpected changes. Though they can be good achievers, they can only earn fame and not money. In other words, they become popular but material success may be a far cry.'

H[105] = 'This number can give fortunes, satisfactory environment, great fame and accumulation of wealth. It will beget good progeny.'

H[106] = 'There will be drastic changes in life. They will experience many problems during their middle age. Their later years will be comfortable. They get into big troubles that cannot be solved easily. This number is not a lucky one. Greed for worldly things will supersede the interest in seeking divine grace.'

H[107] = 'This number will bring fame and success. If they are men, they will have problems due to women and if they are women, it will be from men. Even if they attain wealth, life will not be comfortable. However, they will be famous and influential.'

H[108] = 'This number can give high positions and success. Everything will happen according to their desire. As this number induces its people to make good efforts resulting in success, it is a very lucky number.'

return H 